// process.on('unhandledRejection', (reason, promise) => {
//   // console.log('Unhandled Rejection at:', promise, 'reason: ', reason);
// })

Promise.reject(new Error('error'))
